CREATE TABLE Casos(
    ID SERIAL NOT NULL,
    Caso VARCHAR(50)NOT NULL,
    PRIMARY KEY(ID, Caso)
);


INSERT INTO
 Casos(Caso)
 VALUES
 ('A'),
 ('B'),
 ('C');

SELECT CONCAT(c1, c2, c3) AS permutacion
FROM (
  SELECT 'A' AS c1 UNION SELECT 'B' UNION SELECT 'C'
) AS t1
CROSS JOIN (
  SELECT 'A' AS c2 UNION SELECT 'B' UNION SELECT 'C'
) AS t2
CROSS JOIN (
  SELECT 'A' AS c3 UNION SELECT 'B' UNION SELECT 'C'
) AS t3
WHERE c1 != c2 AND c1 != c3 AND c2 != c3;